import React from 'react';
import { Modal, View, Text, Pressable, ScrollView, ActivityIndicator } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';

interface ExplainModalProps {
  visible: boolean;
  onClose: () => void;
  biteId: number;
  title: string;
}

export default function ExplainModal({ visible, onClose, biteId, title }: ExplainModalProps) {
  const [explanation, setExplanation] = React.useState<string | null>(null);
  const [loading, setLoading] = React.useState(false);

  React.useEffect(() => {
    if (visible && biteId) {
      fetchExplanation();
    }
  }, [visible, biteId]);

  const fetchExplanation = async () => {
    setLoading(true);
    setExplanation(null);
    try {
      const response = await fetch(`${process.env.EXPO_PUBLIC_API_URL}/bites/explain?biteId=${biteId}`);
      const json = await response.json();
      if (json.success) {
        setExplanation(json.data);
      } else {
        setExplanation("AI is catching its breath. Try again in a moment!");
      }
    } catch (error) {
      setExplanation("Connection lost. Please check your signal.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <Modal
      animationType="slide"
      transparent={true}
      visible={visible}
      onRequestClose={onClose}
    >
      <View className="flex-1 bg-slate-950/90 justify-end">
        <Pressable className="flex-1" onPress={onClose} />
        
        <View className="bg-slate-900 rounded-t-[40px] h-[75%] border-t border-slate-800 px-8 pt-4 pb-12">
          {/* Bottom Sheet Handle */}
          <View className="w-12 h-1.5 bg-slate-800 rounded-full self-center mb-8" />
          
          <ScrollView showsVerticalScrollIndicator={false}>
            <View className="mb-8">
              <Text className="text-indigo-500 font-black text-[11px] tracking-[4px] uppercase mb-3">AI Deep Dive</Text>
              <Text className="text-white text-2xl font-black leading-8">{title}</Text>
            </View>

            {loading ? (
              <View className="py-20 items-center justify-center">
                <ActivityIndicator size="large" color="#6366f1" />
                <Text className="text-slate-500 font-bold mt-4 tracking-widest uppercase text-[10px]">Simplifying for you...</Text>
              </View>
            ) : (
              <View>
                <Text className="text-slate-300 text-lg font-medium leading-7 mb-10">
                  {explanation || "Initializing neural insight..."}
                </Text>
                
                <LinearGradient
                  colors={['rgba(99, 102, 241, 0.15)', 'transparent']}
                  className="p-6 rounded-3xl border border-indigo-500/20"
                >
                   <Text className="text-slate-400 text-xs italic text-center leading-5">
                     Insight generated by Gemini AI tailored for career-focused CS students.
                   </Text>
                </LinearGradient>
              </View>
            )}

            <Pressable 
              onPress={onClose}
              className="mt-10 bg-white h-16 rounded-2xl items-center justify-center active:scale-[0.98]"
            >
               <Text className="text-slate-950 font-black text-base uppercase tracking-widest">GOT IT</Text>
            </Pressable>
          </ScrollView>
        </View>
      </View>
    </Modal>
  );
}
