# application-dev.yml
spring:
  datasource:
    writer:
      url: ${DATABASE_WRITER_URL:jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/techbite?useSSL=true&enabledTLSProtocols=TLSv1.2&serverTimezone=UTC&readOnlyPropagatesToServer=false}
      username: ${DATABASE_WRITER_USER:jvZRRNRdZRCKGPP.root}
      password: ${DATABASE_WRITER_PASSWORD:JscNYE6VuCFACo4x}
    replica:
      url: ${DATABASE_REPLICA_URL:jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/techbite?useSSL=true&enabledTLSProtocols=TLSv1.2&serverTimezone=UTC&readOnlyPropagatesToServer=false}
      username: ${DATABASE_REPLICA_USER:jvZRRNRdZRCKGPP.root}
      password: ${DATABASE_REPLICA_PASSWORD:JscNYE6VuCFACo4x}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:${REDIS_HOST:localhost}}
      port: ${SPRING_DATA_REDIS_PORT:${REDIS_PORT:6379}}

app:
  gemini:
    model: gemini-1.5-flash
